# Generated by Django 4.2.7 on 2023-11-20 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('jti', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='JTI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('revoked', models.BooleanField(default=False, verbose_name='Is revoked')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
