name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_EMAIL }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_NAMESPACE }}/${{ secrets.IMAGE_NAME }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: self-hosted
    needs: push_to_registry
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_EMAIL }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull docker image
        run: |
          docker pull ${{ secrets.DOCKER_NAMESPACE }}/${{ secrets.IMAGE_NAME }}:main
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: docker compose
        run: |
          docker-compose -f docker-compose-prod.yml down --remove-orphans
          docker-compose -f docker-compose-prod.yml up -d